// Authoritative Government of India and State Government Schemes Dataset
// Verified against official ministry portals and application gateways

export const AUTHORITATIVE_SCHEMES_DATA = [
  {
    id: 'SCH-PMEGP-001',
    schemeId: 'SCH-PMEGP-001',
    code: 'PMEGP-KVIC-2026',
    name: 'Prime Minister’s Employment Generation Programme (PMEGP)',
    officialName: 'Prime Minister’s Employment Generation Programme (PMEGP)',
    shortName: 'PMEGP',
    category: 'Micro Enterprise',
    governmentDepartment: 'Khadi and Village Industries Commission (KVIC)',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    state: 'Central',
    description: 'Credit-linked subsidy programme to generate self-employment opportunities through establishment of micro-enterprises in non-farm sector.',
    benefits: {
      summary: '15% to 35% margin money subsidy on project cost up to ₹50 Lakh for manufacturing and ₹20 Lakh for service units.',
      subsidyPercentage: 35,
      maxSubsidyAmount: 1750000,
      minLoanAmount: 50000,
      maxLoanAmount: 5000000,
      interestRateAnnual: 8.5,
      moratoriumMonths: 6,
      tenureMonths: 60,
      financialAssistanceDetails: 'Subsidy rate: General category rural 25%, urban 15%. Special category (SC/ST/OBC/Women/Ex-servicemen/PwD) rural 35%, urban 25%.'
    },
    structuredEligibility: [
      { field: 'age', operator: '>=', value: 18, label: 'Applicant must be at least 18 years of age', mandatory: true },
      { field: 'education', operator: 'in', value: ['8th Pass', '10th Pass', '12th Pass', 'Graduate', 'Post Graduate'], label: 'Minimum 8th standard pass required for manufacturing projects above ₹10 Lakh and service projects above ₹5 Lakh', mandatory: false },
      { field: 'existingLoans', operator: '==', value: false, label: 'No past default with banking institutions', mandatory: true }
    ],
    eligibilityRules: [
      'Any individual above 18 years of age',
      'Minimum VIII standard pass for projects costing above ₹10 Lakh in manufacturing and above ₹5 Lakh in service sector',
      'Only new micro-enterprise projects are eligible under PMEGP Phase-I',
      'Existing units and units that have already availed government subsidy are not eligible'
    ],
    requiredDocuments: [
      'Aadhaar Card',
      'PAN Card',
      'Educational Qualification Certificate (VIII standard or above)',
      'Detailed Project Report (DPR) / Cost Breakdown',
      'Caste / Community Certificate (for Special Category subsidy)',
      'Rural Area Certificate (issued by Gram Panchayat for rural claims)',
      'EDP Training Certificate (can be completed post-sanction online)'
    ],
    applicationProcess: [
      'Submit online application through official PMEGP e-Portal (pmegp.msme.gov.in)',
      'Application is routed to District Industries Centre (DIC) or KVIC Nodal Agency for primary document verification',
      'District Level Task Force Committee (DLTFC) reviews proposal and forwards to financing bank branch',
      'Financing bank conducts credit appraisal, sanctions loan, and uploads sanction letter on the portal',
      'Bank dispatches Margin Money (Subsidy) claim to KVIC nodal bank for lock-in deposit (3 years)'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Not specified in the available official source.',
    officialWebsite: 'https://msme.gov.in',
    officialApplicationUrl: 'https://pmegp.msme.gov.in/',
    sourceUrl: 'https://msme.gov.in/our-programmes/prime-ministers-employment-generation-programme-pmegp',
    sourceName: 'Ministry of Micro, Small & Medium Enterprises / KVIC',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 10000000,
    minLoan: 50000,
    maxLoan: 5000000,
    interestRate: 8.5,
    tenureMonths: 60,
    moratoriumMonths: 6,
    projectTypes: ['Manufacturing', 'Service Enterprise', 'Agro Processing', 'Textiles', 'Engineering'],
    supportedStates: ['ALL'],
    partnerTypes: ['Public Sector Bank', 'Regional Rural Bank', 'State Channelizing Agency'],
    subsidyPercentage: 35,
    featured: true,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-SVANIDHI-002',
    schemeId: 'SCH-SVANIDHI-002',
    code: 'PMSVANIDHI-MOHUA-2026',
    name: 'PM Street Vendor’s AtmaNirbhar Nidhi (PM SVANidhi)',
    officialName: 'PM Street Vendor’s AtmaNirbhar Nidhi (PM SVANidhi)',
    shortName: 'PM SVANidhi',
    category: 'Micro Enterprise',
    governmentDepartment: 'Urban Development & Poverty Alleviation',
    ministry: 'Ministry of Housing and Urban Affairs',
    state: 'Central',
    description: 'Central sector scheme for providing affordable collateral-free working capital loan to street vendors to resume their livelihoods.',
    benefits: {
      summary: 'Tranche-based collateral-free loan: 1st tranche up to ₹10,000, 2nd tranche up to ₹20,000, 3rd tranche up to ₹50,000 with 7% interest subsidy.',
      minLoanAmount: 10000,
      maxLoanAmount: 50000,
      interestRateAnnual: 7.0,
      interestSubventionPercent: 7.0,
      moratoriumMonths: 0,
      tenureMonths: 12,
      financialAssistanceDetails: '7% per annum interest subsidy credited directly to bank account quarterly. Cashback up to ₹1,200 per year on digital transactions.'
    },
    structuredEligibility: [
      { field: 'age', operator: '>=', value: 18, label: 'Applicant must be an adult vendor', mandatory: true },
      { field: 'occupation', operator: 'in', value: ['Street Vendor', 'Hawker', 'Artisan', 'Vendor', 'Retail Shop'], label: 'Applicant must be engaged in street vending in urban or peri-urban areas', mandatory: true }
    ],
    eligibilityRules: [
      'Street vendors engaged in vending in urban areas on or before March 24, 2020 (or holding valid vending certificate)',
      'Possession of Certificate of Vending (CoV) / Identity Card issued by Urban Local Body (ULB)',
      'Vendors left out of survey can apply with Letter of Recommendation (LoR) from ULB or Town Vending Committee (TVC)',
      'Timely repayment of 1st tranche qualifies for 2nd tranche up to ₹20,000, and 2nd tranche qualifies for 3rd tranche up to ₹50,000'
    ],
    requiredDocuments: [
      'Aadhaar Card (linked with active mobile number for eKYC)',
      'Certificate of Vending (CoV) OR Urban Local Body Identity Card OR Letter of Recommendation (LoR)',
      'Active Bank Account Details (Passbook / Statement)',
      'Mobile Number linked with bank account'
    ],
    applicationProcess: [
      'Verify mobile number via OTP on pmsvanidhi.mohua.gov.in portal',
      'Select Vending Status: CoV / ID Card holder or Letter of Recommendation applicant',
      'Complete Aadhaar e-KYC authentication',
      'Select preferred financing bank branch or Lending Institution (Lending Partner)',
      'Bank officer conducts digital verification and disburses funds into bank account'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: '12 Months (per tranche)',
    officialWebsite: 'https://mohua.gov.in',
    officialApplicationUrl: 'https://pmsvanidhi.mohua.gov.in/',
    sourceUrl: 'https://pmsvanidhi.mohua.gov.in/',
    sourceName: 'Ministry of Housing and Urban Affairs',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 300000,
    minLoan: 10000,
    maxLoan: 50000,
    interestRate: 7.0,
    tenureMonths: 12,
    moratoriumMonths: 0,
    projectTypes: ['Street Vending', 'Fruit & Vegetable Vending', 'Tea & Food Stall', 'Hawker Service'],
    supportedStates: ['ALL'],
    partnerTypes: ['Public Sector Bank', 'Regional Rural Bank', 'NBFC-MFI', 'Cooperative Bank'],
    featured: true,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-MUDRA-003',
    schemeId: 'SCH-MUDRA-003',
    code: 'PMMY-DFS-2026',
    name: 'Pradhan Mantri Mudra Yojana (PMMY)',
    officialName: 'Pradhan Mantri Mudra Yojana (PMMY)',
    shortName: 'Mudra Loan',
    category: 'Small Business',
    governmentDepartment: 'Department of Financial Services',
    ministry: 'Ministry of Finance',
    state: 'Central',
    description: 'Flagship credit scheme providing collateral-free institutional funding to non-corporate, non-farm small and micro enterprises across Shishu, Kishore, and Tarun categories.',
    benefits: {
      summary: 'Collateral-free business loans up to ₹10 Lakh (extended up to ₹20 Lakh under Tarun Plus for previous borrowers). Low processing fees and concession rates.',
      minLoanAmount: 10000,
      maxLoanAmount: 1000000,
      interestRateAnnual: 8.5,
      moratoriumMonths: 6,
      tenureMonths: 60,
      financialAssistanceDetails: 'Three tiers: Shishu (loans up to ₹50,000), Kishore (₹50,001 to ₹5 Lakh), Tarun (₹5,00,001 to ₹10 Lakh). Tarun Plus (up to ₹20 Lakh) for enterprises with proven credit repayment track record.'
    },
    structuredEligibility: [
      { field: 'age', operator: '>=', value: 18, label: 'Applicant must be at least 18 years of age', mandatory: true },
      { field: 'existingLoans', operator: '==', value: false, label: 'Applicant must not be a defaulter to any bank or financial institution', mandatory: true }
    ],
    eligibilityRules: [
      'Any Indian citizen with a viable business plan for a non-farm income generating activity',
      'Small manufacturing enterprises, service sector units, shopkeepers, fruit/vegetable vendors, truck operators, food service units, repair shops',
      'No collateral requirement; loans are covered under Credit Guarantee Fund for Micro Units (CGFMU)',
      'Enterprise must be in the micro or small business category'
    ],
    requiredDocuments: [
      'Proof of Identity (Aadhaar / Voter ID / Passport / Driving License)',
      'Proof of Residence (Electricity Bill / Ration Card / Aadhaar)',
      'Proof of Business Enterprise (Udyam Registration Certificate / Trade License)',
      'Quotation of machinery, equipment, or items to be purchased',
      'Bank statement for the last 6 months (for Kishore & Tarun categories)',
      'Passport size photographs of applicant/partners'
    ],
    applicationProcess: [
      'Apply online through Udyamimitra portal (udyamimitra.in) or directly at any commercial bank, RRB, or NBFC branch',
      'Submit loan application along with business plan and machinery/inventory quotation',
      'Lender appraises creditworthiness and conducts branch/field appraisal',
      'Sanction letter is issued and loan amount is credited; MUDRA Card issued for working capital overdraft'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Annual review for working capital facilities',
    officialWebsite: 'https://financialservices.gov.in',
    officialApplicationUrl: 'https://www.udyamimitra.in/',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmmy',
    sourceName: 'Department of Financial Services / PMMY',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 20000000,
    minLoan: 10000,
    maxLoan: 1000000,
    interestRate: 8.5,
    tenureMonths: 60,
    moratoriumMonths: 6,
    projectTypes: ['Micro Retail', 'Manufacturing', 'Services', 'Artisan Units', 'Transport Vehicles', 'Food Stalls'],
    supportedStates: ['ALL'],
    partnerTypes: ['Public Sector Bank', 'Regional Rural Bank', 'Small Finance Bank', 'NBFC-MFI'],
    featured: true,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-STANDUP-004',
    schemeId: 'SCH-STANDUP-004',
    code: 'STANDUP-DFS-2026',
    name: 'Stand-Up India Scheme',
    officialName: 'Stand-Up India Scheme for SC/ST and Women Entrepreneurs',
    shortName: 'Stand-Up India',
    category: 'Women Entrepreneurship',
    governmentDepartment: 'Department of Financial Services',
    ministry: 'Ministry of Finance',
    state: 'Central',
    description: 'Bank financing between ₹10 Lakh and ₹100 Lakh to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one woman borrower per bank branch for setting up greenfield enterprises.',
    benefits: {
      summary: 'Composite loans (term loan and working capital) between ₹10 Lakh and ₹100 Lakh for setting up greenfield ventures in manufacturing, services, agri-allied, or trading.',
      minLoanAmount: 1000000,
      maxLoanAmount: 10000000,
      interestRateAnnual: 8.0,
      moratoriumMonths: 18,
      tenureMonths: 84,
      financialAssistanceDetails: 'Composite loan covering up to 85% of project cost. Borrower contribution can be converged with eligible central/state subsidies to bring margin money requirement down.'
    },
    structuredEligibility: [
      { field: 'age', operator: '>=', value: 18, label: 'Applicant must be at least 18 years of age', mandatory: true },
      { field: 'category', operator: 'in', value: ['SC', 'ST', 'General', 'OBC', 'EWS'], label: 'Applicable to SC/ST or Women entrepreneurs (in non-individual enterprises, 51% shareholding must be held by SC/ST or Woman)', mandatory: true }
    ],
    eligibilityRules: [
      'SC/ST and/or woman entrepreneur, above 18 years of age',
      'Loans under the scheme are available for greenfield enterprises only (first-time venture of the beneficiary in manufacturing, services, trading, or agri-allied activities)',
      'In case of non-individual enterprises, 51% of the shareholding and controlling stake should be held by either an SC/ST and/or woman entrepreneur',
      'Borrower should not be in default to any bank or financial institution'
    ],
    requiredDocuments: [
      'Identity Proof (Voter ID / Aadhaar / Passport)',
      'Community Certificate (in case of SC/ST applicants)',
      'Project Report containing technical and financial feasibility details',
      'Certificate of Incorporation / Partnership Deed with proof of 51% shareholding (for entities)',
      'Proof of manufacturing / business premises lease or title',
      'Bank statement for previous 6 months',
      'Pollution control clearance / trade licenses as applicable'
    ],
    applicationProcess: [
      'Apply online through Stand-Up Mitra portal (standupmitra.in)',
      'Select whether applying as "Trainee Borrower" (handholding support needed) or "Ready Borrower"',
      'Portal matches project application to designated Lead District Manager (LDM) or scheduled bank branch',
      'Scheduled commercial bank branch undertakes techno-economic evaluation',
      'Sanction letter issued and margin money / term loan disbursed in tranches'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Annual review',
    officialWebsite: 'https://financialservices.gov.in',
    officialApplicationUrl: 'https://www.standupmitra.in/',
    sourceUrl: 'https://www.standupmitra.in/',
    sourceName: 'Department of Financial Services / SIDBI',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 50000000,
    minLoan: 1000000,
    maxLoan: 10000000,
    interestRate: 8.0,
    tenureMonths: 84,
    moratoriumMonths: 18,
    projectTypes: ['Greenfield Manufacturing', 'Service Ventures', 'Agri-Allied Activities', 'Trading Enterprise'],
    supportedStates: ['ALL'],
    partnerTypes: ['Public Sector Bank', 'Private Sector Scheduled Bank'],
    featured: true,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-PMKISAN-005',
    schemeId: 'SCH-PMKISAN-005',
    code: 'PMKISAN-MOA-2026',
    name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    officialName: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    shortName: 'PM-KISAN',
    category: 'Agriculture & Allied',
    governmentDepartment: 'Department of Agriculture & Farmers Welfare',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    state: 'Central',
    description: 'Direct income support initiative providing financial assistance to all cultivable landholding farmer families across India.',
    benefits: {
      summary: 'Direct income transfer of ₹6,000 per year directly transferred to bank accounts in 3 equal four-monthly installments of ₹2,000.',
      financialAssistanceDetails: '₹6,000 per year paid in three equal installments of ₹2,000 each (Period 1: April-July, Period 2: August-November, Period 3: December-March) through Direct Benefit Transfer (DBT).'
    },
    structuredEligibility: [
      { field: 'occupation', operator: 'in', value: ['Farmer', 'Agriculture', 'Cultivator', 'Farmer Family'], label: 'Farmer families owning cultivable land in their names', mandatory: true },
      { field: 'landHoldingAcres', operator: '>', value: 0, label: 'Must possess cultivable land holding according to state revenue records', mandatory: true }
    ],
    eligibilityRules: [
      'All landholding farmer families who have cultivable landholding in their names as per state land records',
      'Subject to exclusion criteria: institutional landholders, farmer families holding constitutional posts, serving or retired government officers, pensioners drawing ₹10,000+ per month, income tax payees in last assessment year, professionals (doctors, engineers, lawyers, CAs)'
    ],
    requiredDocuments: [
      'Aadhaar Card (e-KYC mandatory via OTP or biometric face authentication)',
      'Land Ownership Record (Khatauni / Patta / Land Mutation Document)',
      'Aadhaar-seeded Bank Account with NPCI mapping',
      'Active Mobile Number linked to Aadhaar'
    ],
    applicationProcess: [
      'Farmer registers on pmkisan.gov.in under "New Farmer Registration" or via nearest Common Service Centre (CSC)',
      'Provide rural/urban classification, Aadhaar number, state, district, and mobile number',
      'Upload land ownership details (Survey/Khasra/Khatauni numbers)',
      'State revenue department verifies land title and approves eligibility',
      'Central Government releases DBT installment directly into Aadhaar-seeded bank account'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Periodic eKYC verification',
    officialWebsite: 'https://agriwelfare.gov.in',
    officialApplicationUrl: 'https://pmkisan.gov.in/RegistrationFormNew.aspx',
    sourceUrl: 'https://pmkisan.gov.in/',
    sourceName: 'Ministry of Agriculture and Farmers Welfare',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 1000000,
    projectTypes: ['Agriculture', 'Crop Cultivation', 'Horticulture'],
    supportedStates: ['ALL'],
    partnerTypes: ['Direct Benefit Transfer (DBT)', 'National Payments Corporation of India (NPCI)'],
    featured: true,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-VISHWAKARMA-006',
    schemeId: 'SCH-VISHWAKARMA-006',
    code: 'PMVISHWAKARMA-MSME-2026',
    name: 'PM Vishwakarma Scheme',
    officialName: 'PM Vishwakarma Scheme for Traditional Artisans and Craftspeople',
    shortName: 'PM Vishwakarma',
    category: 'Artisan & Handloom',
    governmentDepartment: 'Office of the Development Commissioner (MSME)',
    ministry: 'Ministry of Micro, Small and Medium Enterprises & Ministry of Skill Development',
    state: 'Central',
    description: 'Central sector scheme for end-to-end holistic support to traditional artisans and craftspeople working with their hands and tools in 18 notified family-based trades.',
    benefits: {
      summary: 'PM Vishwakarma Certificate & ID, Basic 5-7 days skill training with ₹500/day stipend, Modern Tool-kit incentive ₹15,000, and collateral-free credit up to ₹3 Lakh at 5% concessional rate.',
      minLoanAmount: 100000,
      maxLoanAmount: 300000,
      interestRateAnnual: 5.0,
      interestSubventionPercent: 8.0,
      moratoriumMonths: 6,
      tenureMonths: 30,
      financialAssistanceDetails: 'Collateral-free credit: 1st Tranche of ₹1,00,000 (18 months tenure) and 2nd Tranche of ₹2,00,000 (30 months tenure) at concessional interest rate of 5%, with 8% interest subvention paid by MoMSME. Digital transaction incentives up to ₹100 per month.'
    },
    structuredEligibility: [
      { field: 'age', operator: '>=', value: 18, label: 'Applicant must be at least 18 years of age on registration date', mandatory: true },
      { field: 'occupation', operator: 'in', value: ['Artisan', 'Carpenter', 'Blacksmith', 'Potter', 'Sculptor', 'Cobbler', 'Mason', 'Basket Maker', 'Doll Maker', 'Barber', 'Garland Maker', 'Washerman', 'Tailor', 'Fishing Net Maker', 'Locksmith'], label: 'Engaged in one of the 18 notified traditional family trades', mandatory: true }
    ],
    eligibilityRules: [
      'Artisan or craftsperson working with hands and tools in one of the 18 traditional family trades (Carpenter, Boat Maker, Armorer, Blacksmith, Hammer & Tool Kit Maker, Locksmith, Sculptor, Goldsmith, Potter, Cobbler, Mason, Basket/Mat/Broom Maker, Doll & Toy Maker, Barber, Garland Maker, Washerman, Tailor, Fishing Net Maker)',
      'Minimum age 18 years on the date of registration',
      'Should not have availed loans under similar credit-based schemes (PMEGP, PM SVANidhi, MUDRA) in the past 5 years',
      'Registration and benefits restricted to one member per family'
    ],
    requiredDocuments: [
      'Aadhaar Card (biometric authentication mandatory)',
      'Active mobile number linked with Aadhaar',
      'Bank Account details (Account Number, IFSC)',
      'Ration Card (for family identification confirmation)'
    ],
    applicationProcess: [
      'Registration through Common Service Centre (CSC) on pmvishwakarma.gov.in portal via biometric verification',
      'Stage 1: Verification by Gram Panchayat Head (Panchayat Secretary) or Urban Local Body (ULB)',
      'Stage 2: Vetting by District Implementation Committee (DIC)',
      'Stage 3: Approval by National Steering Committee screening system',
      'Issue of PM Vishwakarma Certificate & Digital ID, followed by 5-7 days skill training and toolkit incentive voucher'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: '30 Months (loan tranche cycle)',
    officialWebsite: 'https://pmvishwakarma.gov.in',
    officialApplicationUrl: 'https://pmvishwakarma.gov.in/',
    sourceUrl: 'https://pmvishwakarma.gov.in/',
    sourceName: 'Ministry of MSME & Ministry of Skill Development',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 500000,
    minLoan: 100000,
    maxLoan: 300000,
    interestRate: 5.0,
    tenureMonths: 30,
    moratoriumMonths: 6,
    projectTypes: ['Carpentry', 'Blacksmithing', 'Pottery', 'Tailoring', 'Masonry', 'Leathercraft', 'Handicraft'],
    supportedStates: ['ALL'],
    partnerTypes: ['Public Sector Bank', 'Regional Rural Bank', 'Common Service Centre (CSC)'],
    featured: true,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-PMFME-007',
    schemeId: 'SCH-PMFME-007',
    code: 'PMFME-MOFPI-2026',
    name: 'PM Formalisation of Micro food processing Enterprises Scheme (PM FME)',
    officialName: 'Pradhan Mantri Formalisation of Micro food processing Enterprises (PM FME)',
    shortName: 'PM FME',
    category: 'Micro Enterprise',
    governmentDepartment: 'Ministry of Food Processing Industries',
    ministry: 'Ministry of Food Processing Industries',
    state: 'Central',
    description: 'Centrally sponsored scheme providing financial, technical, and business support for the upgradation and formalisation of individual and group micro food processing enterprises.',
    benefits: {
      summary: 'Credit-linked capital subsidy of 35% of the eligible project cost with a maximum ceiling of ₹10 Lakh per unit. Seed capital of ₹40,000 per SHG member for working capital.',
      subsidyPercentage: 35,
      maxSubsidyAmount: 1000000,
      minLoanAmount: 100000,
      maxLoanAmount: 5000000,
      interestRateAnnual: 8.5,
      moratoriumMonths: 12,
      tenureMonths: 60,
      financialAssistanceDetails: 'Credit-linked capital subsidy @ 35% of eligible project cost with maximum subsidy of ₹10 Lakh per unit. For Farmer Producer Organizations (FPOs) and Cooperatives, 35% capital grant with common infrastructure support.'
    },
    structuredEligibility: [
      { field: 'age', operator: '>=', value: 18, label: 'Applicant must be at least 18 years of age', mandatory: true },
      { field: 'education', operator: 'in', value: ['8th Pass', '10th Pass', '12th Pass', 'Graduate', 'Post Graduate'], label: 'Minimum 8th standard pass educational qualification', mandatory: false }
    ],
    eligibilityRules: [
      'Individual micro food processing unit or group (SHGs, FPOs, Producer Cooperatives)',
      'Existing micro food processing units undertaking technology upgradation or capacity expansion',
      'New units are eligible under One District One Product (ODOP) focus for that district',
      'Applicant ownership must be proprietary or partnership firm'
    ],
    requiredDocuments: [
      'Aadhaar Card and PAN Card',
      'Bank statement for the last 6 months',
      'Food processing machinery quotation from registered equipment manufacturer',
      'Detailed Project Report (DPR) of food processing venture',
      'Udyam Registration Certificate (or support by District Resource Person to register)',
      'FSSAI registration / license application copy'
    ],
    applicationProcess: [
      'Apply online on National Portal (pmfme.mofpi.gov.in)',
      'District Resource Person (DRP) assists in preparing Detailed Project Report (DPR) and online submission',
      'Application vetted by District Level Committee (DLC) chaired by District Collector',
      'DLC recommends eligible proposal to chosen commercial lending bank branch',
      'Bank sanctions credit and Ministry releases 35% capital subsidy to bank loan account'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Not specified in the available official source.',
    officialWebsite: 'https://mofpi.gov.in',
    officialApplicationUrl: 'https://pmfme.mofpi.gov.in/',
    sourceUrl: 'https://pmfme.mofpi.gov.in/',
    sourceName: 'Ministry of Food Processing Industries',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 10000000,
    minLoan: 100000,
    maxLoan: 5000000,
    interestRate: 8.5,
    tenureMonths: 60,
    moratoriumMonths: 12,
    projectTypes: ['Food Processing', 'Spices Grinding', 'Fruit Pulping', 'Oil Extraction', 'Bakery', 'Grain Milling'],
    supportedStates: ['ALL'],
    partnerTypes: ['Public Sector Bank', 'Regional Rural Bank', 'State Nodal Agency'],
    subsidyPercentage: 35,
    featured: false,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-AHIDF-008',
    schemeId: 'SCH-AHIDF-008',
    code: 'AHIDF-DAHD-2026',
    name: 'Animal Husbandry Infrastructure Development Fund (AHIDF)',
    officialName: 'Animal Husbandry Infrastructure Development Fund (AHIDF)',
    shortName: 'AHIDF',
    category: 'Agriculture & Allied',
    governmentDepartment: 'Department of Animal Husbandry and Dairying',
    ministry: 'Ministry of Fisheries, Animal Husbandry and Dairying',
    state: 'Central',
    description: 'Incentivizing investments by individual entrepreneurs, MSMEs, and FPOs in establishing dairy processing, meat processing, animal feed plants, and breed multiplication farms.',
    benefits: {
      summary: '3% interest subvention on term loans for up to 8 years and credit guarantee coverage up to 25% of loan through NABARD/Credit Guarantee Fund.',
      minLoanAmount: 500000,
      maxLoanAmount: 50000000,
      interestRateAnnual: 6.5,
      interestSubventionPercent: 3.0,
      moratoriumMonths: 24,
      tenureMonths: 96,
      financialAssistanceDetails: 'Up to 90% loan from scheduled banks with 3% interest subvention provided by the Government of India for a maximum period of 8 years (including 2 years moratorium).'
    },
    structuredEligibility: [
      { field: 'age', operator: '>=', value: 18, label: 'Applicant must be at least 18 years of age', mandatory: true }
    ],
    eligibilityRules: [
      'Individual entrepreneurs, private companies, MSMEs, Farmer Producer Organizations (FPOs), Section 8 companies',
      'Projects in dairy processing & value addition, meat processing, animal feed manufacturing, and breed improvement technology',
      'Minimum borrower contribution: 10% for Micro/Small units, 15% for Medium, 25% for other enterprises',
      'Project must be commercially viable with bank credit sanction'
    ],
    requiredDocuments: [
      'Detailed Techno-Economic Feasibility Report (TEFR)',
      'Proof of land ownership or registered lease deed for minimum 10 years',
      'PAN, Aadhaar, and GST registration of applicant enterprise',
      'Audited financial statements / IT returns for preceding 3 years (if applicable)',
      'Pollution control consent letter / NOC'
    ],
    applicationProcess: [
      'Submit application online through AHIDF portal (ahidf.udyamimitra.in)',
      'Project appraisal by Project Management Unit (PMU) of DAHD',
      'Forwarding to applicant’s chosen scheduled commercial bank / NABARD',
      'Lender inspects site, sanctions loan, and uploads documentation',
      'Department credits 3% interest subvention directly to bank on behalf of borrower'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Annual audit review',
    officialWebsite: 'https://dahd.gov.in',
    officialApplicationUrl: 'https://ahidf.udyamimitra.in/',
    sourceUrl: 'https://ahidf.udyamimitra.in/',
    sourceName: 'Department of Animal Husbandry and Dairying',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 100000000,
    minLoan: 500000,
    maxLoan: 50000000,
    interestRate: 6.5,
    tenureMonths: 96,
    moratoriumMonths: 24,
    projectTypes: ['Dairy Processing', 'Animal Feed Manufacturing', 'Breed Multiplication', 'Meat Processing'],
    supportedStates: ['ALL'],
    partnerTypes: ['Public Sector Bank', 'Scheduled Commercial Bank', 'NABARD'],
    featured: false,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-NAPS-009',
    schemeId: 'SCH-NAPS-009',
    code: 'NAPS-MSDE-2026',
    name: 'National Apprenticeship Promotion Scheme (NAPS-2)',
    officialName: 'National Apprenticeship Promotion Scheme (NAPS-2)',
    shortName: 'NAPS-2',
    category: 'Education & Skill',
    governmentDepartment: 'National Skill Development Corporation (NSDC)',
    ministry: 'Ministry of Skill Development and Entrepreneurship',
    state: 'Central',
    description: 'National programme to promote apprenticeship training, incentivize employers, and provide direct stipend support to apprentices engaging in shop-floor skill development.',
    benefits: {
      summary: 'Direct government stipend support of 25% of prescribed stipend up to ₹1,500 per month per apprentice directly transferred via DBT to the apprentice’s bank account.',
      financialAssistanceDetails: 'Direct Benefit Transfer (DBT) of 25% of stipend (up to ₹1,500 per month) credited directly into apprentice bank account. Employers gain industry-ready skilled manpower with zero loan or repayment obligation.'
    },
    structuredEligibility: [
      { field: 'age', operator: '>=', value: 14, label: 'Candidate must be minimum 14 years of age (18 years for hazardous occupations)', mandatory: true }
    ],
    eligibilityRules: [
      'Candidate has attained 14 years of age (18 years for designated hazardous industries)',
      'Possesses educational qualification specified for the designated or optional trade',
      'Must possess an active Aadhaar-linked bank account for receiving DBT stipend payments',
      'Candidate must enter into an apprenticeship training contract with registered employer establishment'
    ],
    requiredDocuments: [
      'Aadhaar Card',
      'Educational Marksheets / Certificates (10th / 12th / ITI / Diploma / Degree as applicable)',
      'Aadhaar-seeded bank account details (Passbook copy)',
      'Passport size photograph'
    ],
    applicationProcess: [
      'Candidate registers on Apprenticeship Portal (apprenticeshipindia.gov.in)',
      'Complete profile, eKYC, and upload educational qualifications',
      'Search for apprenticeship opportunities by trade, location, or company and apply online',
      'Establishment interviews candidate and issues Apprenticeship Contract',
      'Candidate accepts contract online; training commences with monthly DBT stipend support'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Training duration: 6 months to 36 months',
    officialWebsite: 'https://msde.gov.in',
    officialApplicationUrl: 'https://www.apprenticeshipindia.gov.in/candidate-registration',
    sourceUrl: 'https://www.apprenticeshipindia.gov.in/',
    sourceName: 'Ministry of Skill Development and Entrepreneurship',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 1000000,
    projectTypes: ['Skill Development', 'Vocational Apprenticeship', 'Industrial On-the-job Training'],
    supportedStates: ['ALL'],
    partnerTypes: ['Establishments', 'NSDC', 'Direct Benefit Transfer (DBT)'],
    featured: false,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-TNAABCS-010',
    schemeId: 'SCH-TNAABCS-010',
    code: 'AABCS-MSMETN-2026',
    name: 'Annal Ambedkar Business Champions Scheme (AABCS)',
    officialName: 'Annal Ambedkar Business Champions Scheme (AABCS)',
    shortName: 'TN AABCS',
    category: 'Small Business',
    governmentDepartment: 'Department of Micro, Small and Medium Enterprises',
    ministry: 'MSME Department, Government of Tamil Nadu',
    state: 'Tamil Nadu',
    description: 'Special flagship financial assistance scheme by Government of Tamil Nadu to promote economic empowerment and entrepreneurship among Scheduled Caste (SC) and Scheduled Tribe (ST) entrepreneurs.',
    benefits: {
      summary: '35% capital subsidy on project cost up to a maximum subsidy of ₹1.50 Crore, plus 6% interest subvention for a maximum period of 10 years.',
      subsidyPercentage: 35,
      maxSubsidyAmount: 15000000,
      minLoanAmount: 500000,
      maxLoanAmount: 50000000,
      interestRateAnnual: 3.5,
      interestSubventionPercent: 6.0,
      moratoriumMonths: 12,
      tenureMonths: 84,
      financialAssistanceDetails: '35% capital subsidy on project machinery, land, and building costs (up to ₹1.50 Crore). 6% interest subvention directly reimbursed to financing bank for 10 years or term loan period, whichever is earlier.'
    },
    structuredEligibility: [
      { field: 'state', operator: '==', value: 'Tamil Nadu', label: 'Applicant must be a native and resident of Tamil Nadu', mandatory: true },
      { field: 'category', operator: 'in', value: ['SC', 'ST'], label: 'Exclusively for Scheduled Caste (SC) or Scheduled Tribe (ST) entrepreneurs', mandatory: true },
      { field: 'age', operator: '>=', value: 18, label: 'Applicant must be at least 18 years of age', mandatory: true },
      { field: 'age', operator: '<=', value: 55, label: 'Upper age limit of 55 years', mandatory: true }
    ],
    eligibilityRules: [
      'SC / ST entrepreneurs residing in Tamil Nadu',
      'Age between 18 and 55 years on application date',
      'No educational qualification barrier (degree not mandatory)',
      'Manufacturing, service, and commercial business ventures are eligible',
      'New enterprises and existing units undertaking substantial expansion/diversification are eligible'
    ],
    requiredDocuments: [
      'Community Certificate issued by competent revenue authority (SC/ST)',
      'Nativity / Residence Certificate in Tamil Nadu',
      'Aadhaar Card and PAN Card',
      'Project Profile / Detailed Project Report with machinery quotations',
      'Bank Loan Sanction letter from TIIC, commercial bank, or cooperative bank'
    ],
    applicationProcess: [
      'Apply online through Tamil Nadu MSME Single Window Portal (msmeonline.tn.gov.in)',
      'General Manager, District Industries Centre (DIC) / TIIC scrutinizes documentation',
      'District Level Task Force Committee (DLTFC) chaired by District Collector interviews applicant and recommends subsidy sanction',
      'Government of Tamil Nadu releases 35% capital subsidy into applicant escrow account'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: '10 Years interest subvention period',
    officialWebsite: 'https://cms.tn.gov.in',
    officialApplicationUrl: 'https://msmeonline.tn.gov.in/',
    sourceUrl: 'https://msmeonline.tn.gov.in/',
    sourceName: 'MSME Department, Government of Tamil Nadu',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 20000000,
    minLoan: 500000,
    maxLoan: 50000000,
    interestRate: 3.5,
    tenureMonths: 84,
    moratoriumMonths: 12,
    projectTypes: ['Manufacturing', 'Service Sector', 'Commercial Transport', 'Engineering', 'Textiles'],
    supportedStates: ['Tamil Nadu'],
    partnerTypes: ['Tamil Nadu Industrial Investment Corporation (TIIC)', 'Public Sector Bank', 'Regional Rural Bank'],
    subsidyPercentage: 35,
    featured: true,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-TNNEEDS-011',
    schemeId: 'SCH-TNNEEDS-011',
    code: 'NEEDS-MSMETN-2026',
    name: 'New Entrepreneur-cum-Enterprise Development Scheme (NEEDS)',
    officialName: 'New Entrepreneur-cum-Enterprise Development Scheme (NEEDS)',
    shortName: 'TN NEEDS',
    category: 'Small Business',
    governmentDepartment: 'Department of Micro, Small and Medium Enterprises',
    ministry: 'MSME Department, Government of Tamil Nadu',
    state: 'Tamil Nadu',
    description: 'Promoting first-generation educated entrepreneurs in Tamil Nadu by providing credit-linked capital subsidy and interest subvention for setting up manufacturing and service enterprises.',
    benefits: {
      summary: '25% capital subsidy up to ₹75 Lakh on project cost, plus 3% interest subvention for the entire tenure of the loan.',
      subsidyPercentage: 25,
      maxSubsidyAmount: 7500000,
      minLoanAmount: 1000000,
      maxLoanAmount: 50000000,
      interestRateAnnual: 6.0,
      interestSubventionPercent: 3.0,
      moratoriumMonths: 12,
      tenureMonths: 84,
      financialAssistanceDetails: '25% subsidy on project cost (up to ₹75 Lakh). For special categories (women, SC/ST, BC/MBC, PwD, Transgender), additional 10% subsidy rebate available. 3% interest subvention throughout repayment period.'
    },
    structuredEligibility: [
      { field: 'state', operator: '==', value: 'Tamil Nadu', label: 'Resident of Tamil Nadu for minimum 3 years', mandatory: true },
      { field: 'age', operator: '>=', value: 21, label: 'Minimum 21 years of age', mandatory: true },
      { field: 'age', operator: '<=', value: 45, label: 'Up to 35 years for General, up to 45 years for Special Categories (Women/SC/ST/BC/MBC/PwD)', mandatory: true },
      { field: 'education', operator: 'in', value: ['Graduate', 'Post Graduate', 'Diploma', 'ITI'], label: 'Must possess Degree, Diploma, or ITI/Vocational certificate from recognized institution', mandatory: true }
    ],
    eligibilityRules: [
      'First-generation educated entrepreneur residing in Tamil Nadu for at least 3 years',
      'Age: 21 to 35 years for General Category; 21 to 45 years for Special Categories (Women, SC/ST/BC/MBC/Minority/PwD/Transgender)',
      'Educational Qualification: Degree, Diploma, ITI, or Vocational Training certificate from recognized institution',
      'Project cost between ₹10 Lakh and ₹5 Crore for manufacturing and service sectors',
      'Applicant must not have availed subsidy under PMEGP, UYEGP, or other government schemes'
    ],
    requiredDocuments: [
      'Educational Certificates (Degree / Diploma / ITI Marks Card & Transfer Certificate)',
      'Nativity / Domicile Certificate confirming 3+ years residence in Tamil Nadu',
      'Community Certificate (for age relaxation and special category subsidy)',
      'Detailed Project Report (DPR) with machinery quotation and layout',
      'Aadhaar Card and PAN Card'
    ],
    applicationProcess: [
      'Apply online on Tamil Nadu MSME portal (msmeonline.tn.gov.in/needs/)',
      'Upload project proposal, educational credentials, and quotes',
      'District Task Force Committee interviews applicant and evaluates project viability',
      'Selected candidates undergo mandatory Entrepreneurship Development Programme (EDP) training conducted by EDI-TN',
      'Bank branch sanctions credit facility and DIC disburses 25% capital subsidy'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Term loan period',
    officialWebsite: 'https://cms.tn.gov.in',
    officialApplicationUrl: 'https://msmeonline.tn.gov.in/needs/',
    sourceUrl: 'https://msmeonline.tn.gov.in/needs/',
    sourceName: 'MSME Department, Government of Tamil Nadu / DIC',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 25000000,
    minLoan: 1000000,
    maxLoan: 50000000,
    interestRate: 6.0,
    tenureMonths: 84,
    moratoriumMonths: 12,
    projectTypes: ['Manufacturing', 'Food Processing', 'IT & Tech Services', 'Automobile Engineering', 'Plastics'],
    supportedStates: ['Tamil Nadu'],
    partnerTypes: ['TIIC', 'Public Sector Commercial Bank'],
    subsidyPercentage: 25,
    featured: false,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-UPODOP-012',
    schemeId: 'SCH-UPODOP-012',
    code: 'ODOP-DIUP-2026',
    name: 'UP One District One Product (ODOP) Margin Money Scheme',
    officialName: 'Uttar Pradesh One District One Product (ODOP) Margin Money Scheme',
    shortName: 'UP ODOP',
    category: 'Artisan & Handloom',
    governmentDepartment: 'Directorate of Industries and Enterprise Promotion',
    ministry: 'Department of MSME & Export Promotion, Government of Uttar Pradesh',
    state: 'Uttar Pradesh',
    description: 'Promoting indigenous and specialized products and crafts across all 75 districts of Uttar Pradesh through capital margin money subsidy and institutional credit.',
    benefits: {
      summary: 'Margin money subsidy up to 25% (max ₹6.25 Lakh for projects up to ₹25 Lakh; max ₹18.75 Lakh for projects up to ₹50 Lakh) for notified district crafts.',
      subsidyPercentage: 25,
      maxSubsidyAmount: 2000000,
      minLoanAmount: 100000,
      maxLoanAmount: 5000000,
      interestRateAnnual: 8.0,
      moratoriumMonths: 6,
      tenureMonths: 60,
      financialAssistanceDetails: 'Project up to ₹25 Lakh: 25% margin money subsidy (max ₹6.25 Lakh). Project ₹25L to ₹50L: ₹6.25 Lakh or 20% of project cost (whichever is higher). Project ₹50L to ₹5 Crore: ₹10 Lakh or 10% of project cost (max ₹20 Lakh).'
    },
    structuredEligibility: [
      { field: 'state', operator: '==', value: 'Uttar Pradesh', label: 'Resident and native of Uttar Pradesh', mandatory: true },
      { field: 'age', operator: '>=', value: 18, label: 'Applicant must be at least 18 years of age', mandatory: true }
    ],
    eligibilityRules: [
      'Resident of Uttar Pradesh of age 18 years or above',
      'The proposed micro/small enterprise must belong to the notified ODOP product list for that specific district (e.g. Silk Sarees in Varanasi, Leather in Agra/Kanpur, Chikankari in Lucknow, Brassware in Moradabad)',
      'Applicant or family member must not have availed subsidy under any other Central or State government credit scheme for same unit',
      'Minimum educational qualification: 8th pass'
    ],
    requiredDocuments: [
      'Aadhaar Card and Domicile Certificate of Uttar Pradesh',
      'Educational Qualification Certificate (8th pass or above)',
      'Detailed Project Cost Estimate / Machinery Quotation',
      'Affidavit affirming no dual government subsidy availed',
      'Bank Account details'
    ],
    applicationProcess: [
      'Apply online on DIUP portal (diupmsme.upsdc.gov.in)',
      'Select district and corresponding notified ODOP product craft',
      'Deputy Commissioner, District Industries Centre (DIC) inspects application and verifies trade alignment',
      'District Level Task Force Committee (DLTFC) evaluates and forwards to bank',
      'Bank sanctions loan and UP Government deposits margin money subsidy into borrower loan account'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Not specified in the available official source.',
    officialWebsite: 'https://msme.up.gov.in',
    officialApplicationUrl: 'https://odopup.in/',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/odop',
    sourceName: 'Department of MSME & Export Promotion, Government of Uttar Pradesh',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 10000000,
    minLoan: 100000,
    maxLoan: 5000000,
    interestRate: 8.0,
    tenureMonths: 60,
    moratoriumMonths: 6,
    projectTypes: ['Handloom Weaving', 'Brassware', 'Chikankari Embroidery', 'Leather Craft', 'Wood Carving', 'Pottery'],
    supportedStates: ['Uttar Pradesh'],
    partnerTypes: ['District Industries Centre (DIC)', 'Public Sector Bank', 'Regional Rural Bank'],
    subsidyPercentage: 25,
    featured: true,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-UPMMYSY-013',
    schemeId: 'SCH-UPMMYSY-013',
    code: 'MMYSY-DIUP-2026',
    name: 'Mukhyamantri Yuva Swarojgar Yojana (MMYSY)',
    officialName: 'Mukhyamantri Yuva Swarojgar Yojana (MMYSY), Uttar Pradesh',
    shortName: 'UP MMYSY',
    category: 'Small Business',
    governmentDepartment: 'Directorate of Industries',
    ministry: 'Department of MSME & Export Promotion, Government of Uttar Pradesh',
    state: 'Uttar Pradesh',
    description: 'Providing employment and self-reliance opportunities to educated unemployed youth of Uttar Pradesh by providing subsidized credit for setting up industrial and service ventures.',
    benefits: {
      summary: '25% margin money subsidy on project cost (up to ₹6.25 Lakh for industrial sector up to ₹25 Lakh; up to ₹2.50 Lakh for service sector up to ₹10 Lakh).',
      subsidyPercentage: 25,
      maxSubsidyAmount: 625000,
      minLoanAmount: 50000,
      maxLoanAmount: 2500000,
      interestRateAnnual: 8.5,
      moratoriumMonths: 6,
      tenureMonths: 60,
      financialAssistanceDetails: 'Industrial Sector: Max project cost ₹25 Lakh with 25% margin money subsidy (max ₹6.25 Lakh). Service Sector: Max project cost ₹10 Lakh with 25% margin money subsidy (max ₹2.50 Lakh). Subsidy is converted to grant after 2 years of successful operation.'
    },
    structuredEligibility: [
      { field: 'state', operator: '==', value: 'Uttar Pradesh', label: 'Resident and native of Uttar Pradesh', mandatory: true },
      { field: 'age', operator: '>=', value: 18, label: 'Minimum 18 years of age', mandatory: true },
      { field: 'age', operator: '<=', value: 40, label: 'Maximum 40 years of age', mandatory: true },
      { field: 'education', operator: 'in', value: ['10th Pass', '12th Pass', 'Graduate', 'Post Graduate', 'Diploma', 'ITI'], label: 'Minimum 10th (High School) passed from recognized education board', mandatory: true }
    ],
    eligibilityRules: [
      'Citizen and resident of Uttar Pradesh',
      'Age between 18 and 40 years',
      'Minimum educational qualification: High School (10th standard pass)',
      'Applicant should not be employed in government or semi-government service',
      'Applicant must not be a defaulter to any bank or financial institution'
    ],
    requiredDocuments: [
      'Aadhaar Card and Domicile Certificate of UP',
      'High School (10th) Marksheet & Passing Certificate',
      'Detailed Project Profile with machinery and raw material quotations',
      'Caste Certificate (if claiming reserved category preferences)',
      'Bank Account Passbook / Statement'
    ],
    applicationProcess: [
      'Apply online on DIUP portal (diupmsme.upsdc.gov.in/scheme/mmysy)',
      'Submit business proposal and document uploads',
      'Task force committee interviews candidate at District Industries Centre',
      'Sanction by nominated bank branch followed by deposit of 25% margin money'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Not specified in the available official source.',
    officialWebsite: 'https://msme.up.gov.in',
    officialApplicationUrl: 'https://msme.up.gov.in/',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/up-mmysy',
    sourceName: 'Directorate of Industries, Government of Uttar Pradesh',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 10000000,
    minLoan: 50000,
    maxLoan: 2500000,
    interestRate: 8.5,
    tenureMonths: 60,
    moratoriumMonths: 6,
    projectTypes: ['Micro Manufacturing', 'Auto Repair Workshop', 'Printing Press', 'Diagnostic Lab', 'Beauty & Wellness', 'Retail Trade'],
    supportedStates: ['Uttar Pradesh'],
    partnerTypes: ['District Industries Centre (DIC)', 'Public Sector Bank', 'Regional Rural Bank'],
    subsidyPercentage: 25,
    featured: false,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-CGTMSE-014',
    schemeId: 'SCH-CGTMSE-014',
    code: 'CGTMSE-MSME-2026',
    name: 'Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)',
    officialName: 'Credit Guarantee Scheme for Micro and Small Enterprises (CGTMSE)',
    shortName: 'CGTMSE',
    category: 'Term Loan',
    governmentDepartment: 'Credit Guarantee Trust for Micro and Small Enterprises',
    ministry: 'Ministry of Micro, Small and Medium Enterprises & SIDBI',
    state: 'Central',
    description: 'Enabling collateral-free credit flow to micro and small enterprises by providing institutional lenders guarantee coverage against credit default up to ₹500 Lakh.',
    benefits: {
      summary: 'Collateral-free credit facility up to ₹5 Crore with government guarantee coverage up to 85% for micro-enterprises and women/SC/ST entrepreneurs.',
      minLoanAmount: 500000,
      maxLoanAmount: 50000000,
      interestRateAnnual: 9.0,
      moratoriumMonths: 12,
      tenureMonths: 84,
      financialAssistanceDetails: 'Guarantee coverage up to 85% for micro enterprises on loans up to ₹5 Lakh, and up to 75% for loans up to ₹500 Lakh. 85% coverage for women-operated enterprises and SC/ST units.'
    },
    structuredEligibility: [
      { field: 'existingLoans', operator: '==', value: false, label: 'Standard viable credit history without willful defaults', mandatory: true }
    ],
    eligibilityRules: [
      'New and existing Micro and Small Enterprises engaged in manufacturing or service sector',
      'Educational institutions, training institutions, and IT services are eligible',
      'Retail trade activities with credit facilities up to ₹2 Crore eligible under special window',
      'Self-Help Groups (SHGs) and agricultural credit are covered under separate dedicated funds'
    ],
    requiredDocuments: [
      'Udyam Registration Certificate',
      'Audited balance sheets and P&L for past 2 years (for existing enterprises)',
      'Project appraisal report and projected cash flows',
      'PAN Card and GSTIN of enterprise'
    ],
    applicationProcess: [
      'Enterprise approaches Member Lending Institution (Public sector bank, private bank, RRB, or SIDBI)',
      'Lender conducts credit appraisal of project viability without asking for third-party collateral',
      'Upon loan sanction, lender applies to CGTMSE trust online for guarantee cover approval',
      'CGTMSE issues guarantee cover code and lender disburses credit facility'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Annual guarantee fee payment',
    officialWebsite: 'https://www.cgtmse.in',
    officialApplicationUrl: 'https://www.cgtmse.in/',
    sourceUrl: 'https://www.cgtmse.in/',
    sourceName: 'Credit Guarantee Fund Trust for Micro and Small Enterprises / SIDBI',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 100000000,
    minLoan: 500000,
    maxLoan: 50000000,
    interestRate: 9.0,
    tenureMonths: 84,
    moratoriumMonths: 12,
    projectTypes: ['Manufacturing', 'Service Sector', 'Engineering', 'Electronics', 'Packaging', 'Information Technology'],
    supportedStates: ['ALL'],
    partnerTypes: ['Member Lending Institutions (MLIs)', 'Commercial Banks', 'SIDBI'],
    featured: false,
    verified: true,
    sourceType: 'verified_reference'
  },
  {
    id: 'SCH-PMSURYA-015',
    schemeId: 'SCH-PMSURYA-015',
    code: 'PMSURYAGHAR-MNRE-2026',
    name: 'PM Surya Ghar: Muft Bijli Yojana',
    officialName: 'PM Surya Ghar: Muft Bijli Yojana (Rooftop Solar Mission)',
    shortName: 'PM Surya Ghar',
    category: 'Green & Renewable',
    governmentDepartment: 'Rooftop Solar Division',
    ministry: 'Ministry of New and Renewable Energy',
    state: 'Central',
    description: 'National initiative to provide free electricity to households by providing direct capital subsidy for setting up rooftop solar systems and providing access to concessional collateral-free bank loans.',
    benefits: {
      summary: 'Direct Central Financial Assistance: ₹30,000 for 1 kW, ₹60,000 for 2 kW, and ₹78,000 for 3 kW and above rooftop solar systems. Concessional bank credit at ~7% interest.',
      subsidyPercentage: 60,
      maxSubsidyAmount: 78000,
      minLoanAmount: 50000,
      maxLoanAmount: 200000,
      interestRateAnnual: 7.0,
      moratoriumMonths: 6,
      tenureMonths: 84,
      financialAssistanceDetails: '₹30,000 subsidy for 1 kW system; ₹60,000 for 2 kW system; ₹78,000 for 3 kW and above systems for residential households. Special collateral-free bank loans up to ₹2 Lakh available at repo rate + 0.5% (~7% per annum).'
    },
    structuredEligibility: [
      { field: 'age', operator: '>=', value: 18, label: 'Applicant must be an adult consumer', mandatory: true }
    ],
    eligibilityRules: [
      'The applicant must be an Indian citizen possessing residential rooftop property',
      'The household must possess an active grid-connected electricity connection in applicant or family member name',
      'The household must not have previously claimed central rooftop solar subsidy for the same meter connection',
      'Installation must be done through registered solar vendor using Bureau of Indian Standards (BIS) certified equipment'
    ],
    requiredDocuments: [
      'Latest Electricity Bill (showing consumer CA / Connection number)',
      'Proof of Residence / Property Ownership (Electricity Bill / House Tax Receipt)',
      'Aadhaar Card of electricity bill holder',
      'Cancelled Cheque / Bank Passbook (for direct DBT subsidy transfer)'
    ],
    applicationProcess: [
      'Register on National Portal (pmsuryaghar.gov.in) with State, DISCOM name, and Electricity Consumer Account number',
      'Apply online for Rooftop Solar feasibility approval from DISCOM',
      'Upon feasibility approval, select registered empaneled solar vendor and install system',
      'Apply for Net Metering inspection through portal; DISCOM installs net meter',
      'Generate commissioning certificate and submit bank details; subsidy credited via DBT within 30 days'
    ],
    applicationStartDate: null,
    applicationEndDate: null,
    schemeExpiryDate: null,
    isOngoing: true,
    processingPeriod: 'Not specified in the available official source.',
    processingPeriodDays: null,
    renewalPeriod: 'Solar PV Module Performance Warranty: 25 Years',
    officialWebsite: 'https://mnre.gov.in',
    officialApplicationUrl: 'https://pmsuryaghar.gov.in/consumerRegistration',
    sourceUrl: 'https://pmsuryaghar.gov.in/',
    sourceName: 'Ministry of New and Renewable Energy',
    verificationStatus: 'VERIFIED',
    schemeStatus: 'ONGOING',
    fieldVerificationStatus: {
      officialName: true,
      ministry: true,
      department: true,
      description: true,
      benefits: true,
      eligibility: true,
      documents: true,
      applicationUrl: true,
      applicationDates: false
    },
    lastVerifiedAt: '2026-09-26T12:00:00Z',
    lastUpdatedAt: '2026-09-26T12:00:00Z',
    version: '2026.1',
    minIncome: 0,
    maxIncome: 10000000,
    minLoan: 50000,
    maxLoan: 200000,
    interestRate: 7.0,
    tenureMonths: 84,
    moratoriumMonths: 6,
    projectTypes: ['Rooftop Solar Installation', 'Renewable Energy', 'Solar Power Generation'],
    supportedStates: ['ALL'],
    partnerTypes: ['Distribution Companies (DISCOMs)', 'Scheduled Commercial Banks', 'IREDA'],
    subsidyPercentage: 60,
    featured: true,
    verified: true,
    sourceType: 'verified_reference'
  }
];
